# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-PopupTreeSelect-Dynamic
version:      1.1
version_from: Dynamic.pm
installdirs:  site
requires:
    HTML::PopupTreeSelect:         1.5
    HTML::Prototype:               1.33

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
